name: Bug Report
description: Report a bug or issue that you found.
title: '[BUG]: bug name'
labels: [bug]
body:

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: Short description of the bug. Provide images/code if applicable.
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 'Screenshots'
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false

  - type: textarea
    id: expected-behaviour
    attributes:
      label: 'Expected Behaviour'
      description: Describe the expected behavior.
      placeholder: Short and explicit description of your desired behavior...
    validations:
      required: true

  - type: textarea
    id: how-to-replicate
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 'Error Message'
      description: Copy and paste any relevant error message.
      render: bash
    validations:
      required: false

  - type: textarea
    id: extra-information
    attributes:
      label: Additional information
      description: Is there anything else we should know about this bug?

  - type: dropdown
    id: browsers
    attributes:
      label: 'Browsers'
      description: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera
        - All
    validations:
      required: false