name: Feature Request
description: Suggest a new feature or enhancement for the Reputation Framework.
title: '[FEATURE]: feature name'
labels: [enhancement]
body:

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Short description of the feature. Provide any relevant details.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve?
      placeholder: Explain why this feature should be implemented
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 'Screenshots'
      description: If applicable, add screenshots to help explain the new feature.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Additional context