name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * *' # Runs Everyday.

jobs:
  update_contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Run contributor fetch script.
        run: |
          gem install octokit
          ruby fetch_contributor_data.rb

      - name: Commit and push updated contributors data.
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _data/contributors.json
          git commit -m "Update contributors data."
          git push
